# Generated by Django 3.2.16 on 2023-02-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20230215_1955'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='order_location', to='location.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
