# Generated by Django 3.2.16 on 2023-02-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20230130_2127'),
        ('checkout', '0003_auto_20230226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item'),
        ),
    ]
