# Generated by Django 3.2.16 on 2023-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_category',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='special_offer',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menu_category',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='special_offer',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
