# Generated by Django 3.2.16 on 2023-01-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230129_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_item',
            options={'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='special_offer',
            options={'verbose_name_plural': 'Special Offers'},
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menu_category'),
        ),
    ]
