# Generated by Django 3.2.16 on 2023-01-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20230130_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='category',
        ),
        migrations.AddField(
            model_name='menu_category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menu_item'),
        ),
    ]
