# Generated by Django 3.2.16 on 2023-03-09 16:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20230307_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('icon', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='allergens',
        ),
        migrations.DeleteModel(
            name='Special_Offer',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='allergen', to='menu.Allergens'),
        ),
    ]
