# Generated by Django 3.2.16 on 2023-03-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20230309_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergens',
            new_name='Allergen',
        ),
    ]
